tunnel: $CLOUDFLARE_TUNNEL_UUID
credentials-file: /etc/cloudflared/$CLOUDFLARE_TUNNEL_UUID.json

ingress:
  - hostname: $OLLAMA_PUBLIC_HOSTNAME
    service: $OLLAMA_LOCAL_URL
    originRequest:
      httpHostHeader: $OLLAMA_ORIGIN_HOST_HEADER
  - service: http_status:404
